name: Production CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Ticketing-ENV

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Deploy using ssh
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ secrets.PROD_PRIVATE_KEY }}
          port: 22
          debug: true
          script: |
            cd production/Sade-Ticketing-BE
            git pull origin main
            npm i
            yes | npm run mg:push
            npm run db:seed
            pm2 restart 2
