name: Staging CD

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Ticketing-ENV

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          
      - name: Deploy using ssh
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USERNAME }}
          key: ${{ secrets.STAGING_PRIVATE_KEY }}
          port: 22
          debug: true
          script: |
            cd staging/ticketing
            git pull origin dev
            npm i
            pm2 restart 2
